package com.memoryjournal.app
import androidx.compose.runtime.snapshotFlow
import com.google.firebase.firestore.DocumentSnapshot
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

class FirebaseRepository {
    private val db = FirebaseFirestore.getInstance()

    //entries in the db
    private val entriesCollection = db.collection("entries")

    //save new entry to db
    //runs asynchronously
    suspend fun saveEntry(entry: JournalEntry):String {
        //have the id autogenerated from firestore
        val doc = entriesCollection.document()
        val entryWithId = entry.copy(
            id = doc.id, createdAt = System.currentTimeMillis()
        )
        doc.set(entryToMap(entryWithId)).await()
        return doc.id
    }
    //flow - whenever db changes, ui updated
    fun getEntries(): Flow<List<JournalEntry>> = callbackFlow {
        val listener = entriesCollection.orderBy("createdAt", Query.Direction.DESCENDING)
            .addSnapshotListener { snapshot,  error ->
                if(error!= null){
                    close(error)
                    return@addSnapshotListener
                }
                //convert docs to journal entry objects
                val entries = snapshot?.documents?.mapNotNull {
                    doc -> doctoJournalEntry(doc)
                } ?:emptyList()
                trySend(entries)//to UI
            }
        //screen change, stop listening
        awaitClose { listener.remove() }
    }

    //del journal entry
    suspend fun deleteEntry(entryId:String){
        entriesCollection.document(entryId).delete().await()
    }
    //journal entry to firestore map
    private fun entryToMap(entry: JournalEntry): Map<String,Any?>{
        return buildMap {
            put("id", entry.id)
            put("title", entry.title)
            put("text", entry.text)
            put("createdAt", entry.createdAt)
            entry.photoPath?.let { put("photoPath", it) }
            entry.latitude?.let { put("latitude", it) }
            entry.longitude?.let { put("longitude", it) }
            entry.locationName?.let { put("locationName", it) }
            entry.weather?.let { put("weather", it) }
        }
    }
    //firestore to journal entry obj
    private fun doctoJournalEntry(doc: DocumentSnapshot): JournalEntry?{
        return try {
            JournalEntry(
                id = doc.getString("id") ?: doc.id,
                title = doc.getString("title") ?: "",
                text = doc.getString("text") ?: "",
                photoPath = doc.getString("photoPath"),
                latitude = doc.getDouble("latitude"),
                longitude = doc.getDouble("longitude"),
                locationName = doc.getString("locationName"),
                weather = doc.getString("weather"),
                createdAt = doc.getLong("createdAt") ?: 0L
            )
        } catch (e: Exception) {
            null
        }
    }

}

